#=================================================
# https://github.com/Live-ID/OpenWrt-Actions
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: Tony
# Blog: https://bit.do/TonyLee
#=================================================

#name: OpenWrt WR703N OpenVPN SSR
#name: OpenWrt WR703N OpenVPN SSR
#name: OpenWrt WR703N OpenVPN SSR
#name: OpenWrt WR720N OpenVPN SSR
#name: OpenWrt WR720N SSR troja
#name: OpenWRT for N1
name: OpenWRT for WR941Nv4

on: 
  release:
    types: [published]
  push:
    branches: 
      - master
    paths:
      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
#  watch:
#    types: [started]
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        echo "Deleting files, please wait ..."
        sudo rm -rf /usr/share/dotnet /etc/apt/sources.list.d/*
        sudo swapoff /swapfile
        sudo rm -f /swapfile
        #docker rmi `docker images -q`
        #sudo -E apt-get -q purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        curl -fsSL https://raw.githubusercontent.com/P3TERX/dotfiles/master/.bashrc >> ~/.bashrc
        sudo ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

    - name: Clone source code
      env: 
       ## REPO_URL: https://github.com/coolsnowwolf/lede
       ## REPO_URL: https://github.com/openwrt/openwrt
       ## REPO_URL: https://github.com/openwrt/openwrt
       ## REPO_URL: https://github.com/a520ass/openwrt
         REPO_URL: https://github.com/coolsnowwolf/lede
         REPO_BRANCH: master
      run: git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt

    - name: Update feeds
      run: cd openwrt && ./scripts/feeds update -a

    - name: Install feeds
      run: cd openwrt && ./scripts/feeds install -a

    - name: Custom 个性化设置一些文件
      run: |
          cd openwrt
          #
          ## sed -i 's/被替换的内容/要替换成的内容/' package/lean/default-settings/files/zzz-default-setting
          sed -i 's/R9.12.03/by Tony 2019/' package\/lean\/default-settings\/files\/zzz-default-settings
          sed -i 's/192.168.1.1/192.168.2.1/' package\/base-files\/files\/bin\/config_generate
          ##sed -i 's/WDR7400/WDR7600/' package\/base-files\/files\/bin\/config_generate
          sed -i 's/OpenWrt/NanoPi/' package\/base-files\/files\/bin\/config_generate
          sed -i 's/.ssid=OpenWrt/.ssid=NanoPi-WiFi/' package\/kernel\/mac80211\/files\/lib\/wifi\/mac80211.sh
          sed -i 's/.encryption=none/.encryption=psk2\n	    		set wireless.default_radio\${devidx}.key=password\n/' package\/kernel\/mac80211\/files\/lib\/wifi\/mac80211.sh
      
    - name: Custom Applications 增加应用软件
      run: |
          cd friendlywrt-h5/friendlywrt/package
          git clone https://github.com/Baozisoftware/luci-app-koolproxy
          git clone https://github.com/vernesong/OpenClash.git
          git clone https://github.com/destan19/OpenAppFilter.git
          git clone https://github.com/tty228/luci-app-serverchan.git
          git clone https://github.com/BoringCat/luci-app-mentohust.git
          git clone https://github.com/ilya-fedin/pihole-openwrt.git
          
    - name: Load custom configuration 
      env:
       # CONFIG_FILE: '.config'
       # CONFIG_FILE: 'OpenWRT-N1.config'  
       # CONFIG_FILE: '.config'  
        CONFIG_FILE: 'OpenWRT_WR941N_v4_1.config' 
        DIY_SH: 'diy.sh'
      run: |
        [ -e files ] && mv files openwrt/files
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
        chmod +x $DIY_SH
        cd openwrt
        ../$DIY_SH
        make defconfig

#    - name: SSH connection to Actions
#      uses: P3TERX/debugger-action@master
    - name: SSH connection to Actions
      uses: P3TERX/debugger-action@master

    - name: Download package
      run: |
        cd openwrt && make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: Multi-thread compile
      run: |
        cd openwrt
        echo -e "$(nproc) thread compile"
        make -j$(nproc)

    - name: Single-thread compile
      if: failure()
      run: |
        cd openwrt
        make -j1 V=s

    - name: Upload bin directory
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: OpenWrt_bin
        path: openwrt/bin openwrt/.config
        

    - name: Organize files
      if: always()
      run: |
        cp openwrt/.config ./artifact/
        cd openwrt/bin/targets/*/*
        rm -rf packages
        echo "::set-env name=FIRMWARE::$(pwd)"

    - name: Upload firmware
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: WR941N_firmware
        path: ${{ env.FIRMWARE }}
          
